server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://10.1.6.10:3306/lxh
    username: twodfire
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.demo.entity # 注意：对应实体类的路径

